# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the archives look like:
    # - project_Linux_x86_64.tar.gz
    # - project_Darwin_x86_64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

brews:
  - repository:
      owner: k0wl0n
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    
    commit_author:
      name: k0wl0n
      email: wahyuanggana1@gmail.com

    directory: Formula
    
    name: steam-autoshutdown
    homepage: "https://github.com/k0wl0n/steam-autoshutdown"
    description: "Automatically shuts down your computer when Steam downloads finish."
    license: "MIT"
    
    test: |
      system "#{bin}/steam-autoshutdown --version"

scoops:
  - repository:
      owner: k0wl0n
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"
    
    commit_author:
      name: k0wl0n
      email: wahyuanggana1@gmail.com

    homepage: "https://github.com/k0wl0n/steam-autoshutdown"
    description: "Automatically shuts down your computer when Steam downloads finish."
    license: "MIT"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
